//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Club { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
